### ISSUE TITLE
Vertcoin add-on out of date, unable to verify transactions

### ISSUE THREAD

**Issue by sjexoq** [WeProgramIT/cryptowoo-vertcoin-addon#3]
The Vertcoin add-on is out of date, you're using http://explorer.vertcoin.info to verify the transaction but that site hasn't been updated in years and is out of service.

Please use either the official Vertcoin site https://insight.vertcoin.org or https://bitinfocharts.com which are both up to date and fully working.

**Comment by Olsm** [comment]
explorer.vertcoin.info is still operational. However we are aware it has been regularly out of sync with the blockchain causing transactiosn to time out.

We have made the possibility to use a custom insight api explorer. Chose custom in the exchange rate api option and add for example "https://insight.vertcoin.org"
